name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build the software package
      run: |
        sudo mkdir -p /Library/HelloWorld3/TempBuild
        sudo chown $(whoami) /Library/HelloWorld3/TempBuild
        make -C mac TEMP_INSTALL_ROOT=/Library/HelloWorld3/TempBuild -j2 dist/HelloWorld3.app.zip
    - uses: actions/upload-artifact@v1
      with:
        name: HelloWorld3.app.zip
        path: mac/dist/HelloWorld3.app.zip
